Delete source for documentation that has been moved to docs platform
mongodb/mongo-cxx-driver pull request #1120
Opened 2024-03-22 18:33 UTC by rachel-mack

I've rewritten the index page for the mongocxx index to direct people to [new C++ driver docs](https://www.mongodb.com/docs/languages/cpp/drivers/current/), and deleted the transferred source code.

2024-03-22 20:36 UTC, rachel-mack commented
Per a conversation with Ezra, it doesn't look like the test failures are related to the files I've deleted.

2024-03-25 17:28 UTC, kevinAlbs requested changes
Thank you for the PR. I expect this will result in 404's for previously working links. I added a custom 404 page on the `gh-pages` branch to link to the new documentation. Example: https://mongocxx.org/notfound

---

Here are other requested changes:

Remove other no-longer-needed pages:

- content/mongocxx-v3/api-abi-versioning.md
- content/mongocxx-v3/installation
- content/mongocxx-v3/policies

Update other references of `https://mongocxx.org/` (excluding referencs to Doxygen API docs: `https://mongocxx.org/api`) to refer to the new pages. There are references in README.md, and in code ([example](https://github.com/mongodb/mongo-cxx-driver/blob/2709febdbc4bbfce609722aed399348a1793fb66/examples/mongocxx/tutorial.cpp#L3)).

2024-03-26 17:00 UTC, kevinAlbs approved these changes
LGTM with a tweak to the release steps.

2024-03-26 17:00 UTC, kevinAlbs commented on etc/releasing.md
>     new latest stable version to download.
Suggest limiting this step to stable (not release candidate) releases. Suggest recommending creating DOCSP ticket to simplify the process. Note updating version in snooty.toml and home page table:

```suggestion
- If the release was not a release candidate, ensure a [DOCSP JIRA ticket](https://jira.mongodb.org/projects/DOCSP/issues/) is created to request updating:

  - the `Installing the MongoDB C driver` section of the [Advanced Installation documentation](https://github.com/mongodb/docs-cpp/blob/master/source/installation/advanced.txt) to reflect libmongoc requirements
  - the `Driver Status by Family and Version` section of the [home page](https://github.com/mongodb/docs-cpp/blob/master/source/installation/linux.txt)
  - the [C++ driver version](https://github.com/mongodb/docs-cpp/blob/e13d787967172220ae19e5d78df61e2071735f0f/snooty.toml#L20-L21).
```

2024-03-26 18:03 UTC, merged