Add a check on the client in the pool::acquire() function and throw e…
mongodb/mongo-cxx-driver pull request #1205
Opened 2024-09-08 13:32 UTC by Klizzardy

(This pull request fix one minor bug)
Symptom: When the uri parameter 'waitQueueTimeoutMS' was enabled and set to a smaller value (e.g. 100), the function 'mongoc_client_pool' may return a NULL client.
Solution:  Add a check in the function 'pool::entry pool::acquire()', and throw an exception when correct client was not returned.

2024-09-09 19:41 UTC, kevinAlbs requested changes
Thank you for the PR @Klizzardy.

2024-09-09 19:41 UTC, kevinAlbs commented on src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
> +        throw exception{ error_code::k_invalid_client_object,
Suggest defining a new error code. `k_invalid_client_object` is associated [with the message](https://github.com/mongodb/mongo-cxx-driver/blob/54693de778fffb56571853d7f22c7e972d53b845/src/mongocxx/lib/mongocxx/v_noabi/mongocxx/exception/error_code.cpp#L38) `invalid use of default constructed or moved-from mongocxx::client object`.

2024-09-09 19:41 UTC, kevinAlbs commented on src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
Suggest adding a regression test to `src/mongocxx/test/pool.cpp`:

```c++
TEST_CASE("acquiring a client throws if waitQueueTimeoutMS expires", "[pool]") {
    instance::current();
    auto uri = mongocxx::uri{"mongodb://localhost:27017/?waitQueueTimeoutMS=1&maxPoolSize=1"};
    mongocxx::pool pool{uri, options::pool(test_util::add_test_server_api())};
    // Acquire only available client:
    auto client = pool.acquire();
    // Try to acquire again. Expect timeout:
    REQUIRE_THROWS_WITH(pool.acquire(),
                        Catch::Matchers::ContainsSubstring("failed to acquire client"));
}
```

2024-09-10 01:39 UTC, Klizzardy commented
Thank you for your suggestions. They really helped me understand mongocxx better. I've made all the changes you recommended, and the updated code has been committed. @kevinAlbs

2024-09-10 13:04 UTC, kevinAlbs requested changes

2024-09-10 13:52 UTC, Klizzardy commented
Thanks for your patience. I have updated the code based on your suggestions. If there are any other issues, feel free to let me know. @kevinAlbs

2024-09-10 18:41 UTC, kevinAlbs approved these changes
LGTM with additional minor requested changes.

2024-09-10 19:29 UTC, eramongodb requested changes

2024-09-10 19:29 UTC, eramongodb commented on src/mongocxx/test/pool.cpp
> +    auto client = pool.acquire();
```suggestion
    auto client = pool.acquire();
    CHECK(client);
```
Add assertion of the acquired pool entry (+ address unused variable warnings).

2024-09-10 19:29 UTC, eramongodb commented on src/mongocxx/lib/mongocxx/v_noabi/mongocxx/exception/error_code.cpp
> +                       "possibly due to curi-parameter 'waitQueueTimeoutMS' limits";
```suggestion
            case error_code::k_pool_wait_queue_timeout:
                return "timed out while waiting for a client to be returned to the pool";
```
Recommend being specific with the error code name and corresponding message. `mongoc_client_pool_pop` only returns `NULL` on wait queue timeouts. Therefore, this error code should be named `k_pool_wait_queue_timeout` or similar.

2024-09-11 04:43 UTC, Klizzardy commented
All changes have been applied to the branch. If there are any other issues, please feel free to point them out. @kevinAlbs @eramongodb

2024-09-11 14:04 UTC, eramongodb approved these changes
Some formatting changes remaining; otherwise, LGTM.

2024-09-11 14:04 UTC, eramongodb commented on src/mongocxx/lib/mongocxx/v_noabi/mongocxx/pool.cpp
> +            "failed to acquire client, possibly due to parameter 'waitQueueTimeoutMS' limits." };
```suggestion
        throw exception{
            error_code::k_pool_wait_queue_timeout,
            "failed to acquire client, possibly due to parameter 'waitQueueTimeoutMS' limits."};
```
Formatting.

2024-09-11 14:04 UTC, eramongodb commented on src/mongocxx/include/mongocxx/v_noabi/mongocxx/exception/error_code.hpp
> +    k_pool_wait_queue_timeout,
```suggestion

    // Timed out while waiting for a client to be returned to the pool
    k_pool_wait_queue_timeout,
```
Formatting (remove trailing whitespace).

2024-09-11 18:07 UTC, merged