CXX-2995 Bump minimum required C Driver version to 1.29.0
mongodb/mongo-cxx-driver pull request #1275
Opened 2024-11-19 16:25 UTC by eramongodb

Followup to https://github.com/mongodb/mongo-cxx-driver/pull/1235 and the release of C Driver 1.29.0. Update of the Augmented SBOM may require waiting for Silk to complete its nightly(?) update.

2024-11-19 16:55 UTC, kevinAlbs approved these changes

2024-11-19 17:01 UTC, kevinAlbs requested changes
Replace calls to `bson_as_json` => `bson_as_legacy_extended_json` and `bson_array_as_json` => `bson_array_as_legacy_extended_json` to account for deprecations of CDRIVER-5700.

2024-11-19 17:32 UTC, kevinAlbs approved these changes

2024-11-19 21:20 UTC, eramongodb commented
Latest changes (sans formatting) verified by [this patch](https://spruce.mongodb.com/version/673cfa5ac15c7b0007ea1f9e).

2024-11-20 13:16 UTC, kevinAlbs approved these changes

2024-11-20 15:12 UTC, merged