CXX-2046 Implement operator[] for bsoncxx::document::value
mongodb/mongo-cxx-driver pull request #723
Opened 2020-09-15 15:49 UTC by rayangler

2020-09-16 20:10 UTC, bazile-clyde approved these changes
LGTM! Great work!

2020-09-16 20:24 UTC, samantharitter requested changes
Code changes look fine to me, I just requested an additional test case.

2020-09-16 20:24 UTC, samantharitter commented on src/bsoncxx/test/bson_get_values.cpp
> +    REQUIRE(doc["test_array"][2].get_int32() == view["test_array"][2].get_int32());
Could you please add a test that attempts to find a key that does not exist in the document?

2020-09-21 15:02 UTC, samantharitter approved these changes
LGTM!

2020-09-22 13:22 UTC, kevinAlbs approved these changes
LGTM! This is a good convenience.

2020-09-22 18:40 UTC, merged